license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Groupix05/DynamicTrees-Dense-Trees/issues"

[[mods]]
modId="dense_dynamictrees"
version="${file.jarVersion}"
displayName="Dynamic Trees for Dense Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-dense-trees"
logoFile="logo.png"
credits=""
authors="WenXin2"
description='''
Adds Dynamic Trees compatibility for Dense Trees.
'''

[[dependencies.dense_dynamictrees]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dense_dynamictrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dense_dynamictrees]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dense_dynamictrees]]
    modId="densetrees"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="AFTER"
    side="BOTH"
