license="MIT"
modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Groupix05/DynamicTrees-Dense-Trees/issues"

[[mods]]
modId="dense_dynamictrees"
version="${file.jarVersion}"
displayName="Dynamic Trees for Dense Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-dense-trees"
logoFile="logo.png"
credits=""
authors="WenXin2"
description='''
Adds Dynamic Trees compatibility for Dense Trees.
'''

[[dependencies.dense_dynamictrees]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.201,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dense_dynamictrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dense_dynamictrees]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.5.0-BETA07,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dense_dynamictrees]]
    modId="densetrees"
    mandatory=true
    versionRange="[8.0.0,)"
    ordering="AFTER"
    side="BOTH"
